## ¿Por qué Numpy y Pandas?



- Numpy: Es una librería para el cálculo numérico y manejo de arrays.
  
  ¿Por qué Numpy?
  - Velocidad, más rapido de manejar que una lista de Python
  - Tamaño, optimiza el almacenamiento en memoria
  - Tipos de datos


- Pandas: Es una librería para la manipulación y analisis de datos. 
  
  ¿Por qué Pandas?
  - Velocidad, hereda las bondades de Numpy
  - Poco código para manipular datos
  - Múltiples formatos de archivos
  - Alineación inteligente, ordena los datos de manera automática

Enlaces:
- [Slides del curso](https://static.platzi.com/media/public/uploads/slides-numpy-pandas_8e1aa25f-6bfd-4d37-ad25-fead42a29830.pdf)
- [Ventajas de usar Numpy](https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists)
- [Numpy](https://numpy.org/)
- [Pandas](https://pandas.pydata.org/docs/getting_started/index.html)

# Numpy

El Array es la estructura central de Numpy, representa datos de una manera estructurada y se puede acceder a sus elementos a traves del indexado.


[Tutorial Numpy](https://platzi.com/blog/numpy/)

[Numpy User Guide](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

In [1]:
# Importando Numpy
import numpy as np

In [2]:
# Definiendo una lista en Python
lista = [1,2,3,4,5,6,7,8,9]
print(lista, type(lista))

[1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [3]:
# Definiendo un Array en Numpy
arr = np.array(lista)
print(arr, type(arr))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [4]:
# Definiendo una Matriz por medio de listas
matriz = [[1,2,3], [4,5,6], [7,8,9]]
print(matriz, type(matriz))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>


In [5]:
# Definiendo una Matriz en Numpy
matrix = np.array(matriz)
print(matrix, type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [6]:
# Definiendo un Tensor por medio de listas
tensor = [[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]
print(tensor, type(tensor))

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]] <class 'list'>


In [7]:
# Definiendo un Tensor en Numpy
tens = np.array(tensor)
print(tens, type(tens))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] <class 'numpy.ndarray'>


 ### Indices y Slicing.

[Indexing on ndarrays](https://numpy.org/doc/stable/user/basics.indexing.html)

In [8]:
# Indexando el array
print(arr)

print(arr[0])
print(arr[2:6])

[1 2 3 4 5 6 7 8 9]
1
[3 4 5 6]


In [9]:
# Indexando la matriz
print(matrix)

# matrix[filas, columnas]
print(matrix[1,1])
print(matrix[1:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[[4 5]
 [7 8]]


In [10]:
# Indexando el Tensor
print(tens)

# tens[profundidad, filas, columnas]
print(tens[1])
print(tens[1,1,1])
print(tens[1,1,:])

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[5 6]
 [7 8]]
8
[7 8]


[Ejemplo matriz de tres dimensiones o tensor](https://deepnote.com/project/NP-and-PD-McWhj16VRLKOLngJ6iL3dw/%2FTutorial%203D.ipynb)

### Tipos de datos

[Basic types](https://numpy.org/doc/stable/user/basics.types.html)

[Arrays dtypes](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

In [11]:
array1 = np.array([1,2,3,4])
print(array1)
print(array1.dtype) # con dtype podemos conocer el tipo de dato

[1 2 3 4]
int64


In [12]:
# podemos definir el tipo de dato
array1 = np.array([1,2,3,4], dtype='float64')
print(array1)
print(array1.dtype)

[1. 2. 3. 4.]
float64


In [13]:
# para redefinir el tipo de dato
array1 = array1.astype(np.int64)
print(array1)

[1 2 3 4]


In [14]:
array2 = np.array([0,1,2,3])
array2 = array2.astype(np.bool_)
print(array2)

[False  True  True  True]


In [15]:
array2 = np.array([0,1,2,3])
array2 = array2.astype(np.str_)
print(array2)

['0' '1' '2' '3']


### Dimensiones

Dimensiones de los datos.

- Escalar: dim = 0
- Vector: dim = 1
- Matriz: dim = 2
- Tensor: dim >= 3

![Imagen](https://static.platzi.com/media/user_upload/dimensiones-05e2590d-270a-4092-bca2-590b92cc0330.jpg)

In [16]:
escalar = np.array(42)
print(escalar) 
print(escalar.ndim)
print(escalar.shape)

42
0
()


In [17]:
vector = np.array([1,2,3])
print(vector)
print(vector.ndim)
print(vector.shape)

[1 2 3]
1
(3,)


In [18]:
matriz = np.array([[1,2,3], [4,5,6]])
print(matriz)
print(matriz.ndim)
print(matriz.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [19]:
tensor3D = np.array([[[1,2,3],
                      [4,5,6],
                      [1,1,1]],
                     [[7,8,9],
                      [10,11,12],
                      [0,0,0]]])
print(tensor3D)
print(tensor3D.ndim)
print(tensor3D.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  1  1]]

 [[ 7  8  9]
  [10 11 12]
  [ 0  0  0]]]
3
(2, 3, 3)


### Agregar o eliminar dimensiones

In [20]:
# Agregar dimensiones con ndmin
vector = np.array([1,2,3], ndmin=4)
print(vector)
print(vector.ndim)

[[[[1 2 3]]]]
4


In [21]:
# Expandir una dimension al array en sus ejes

# axis=0 es para filas y axis=1 para columnas
expand = np.expand_dims(np.array([4,5,6]), axis=0) 
print(expand)
print(expand.ndim)
print(expand.shape)

[[4 5 6]]
2
(1, 3)


In [22]:
# Eliminar las dimensiones con squeeze
print(vector, vector.ndim)
vector2 = np.squeeze(vector) 
# squeeze() comprime el numero de dimensiones que no se utilizan
print(vector2, vector2.ndim)

[[[[1 2 3]]]] 4
[1 2 3] 1


### Creando arrays

Podemos crear nuestros arrays directamente desde Numpy.

[Array creation](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [23]:
# arange()
print(np.arange(5))
print(np.arange(0,20,2))

[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14 16 18]


In [24]:
# zeros()
print(np.zeros(5))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# zeros_like() 
a = np.array([[1,2],[3,4]])
print(a)
# recibe un array y retorna otro con la misma dimension pero de puros ceros
b = np.zeros_like(a)
print(b)

[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


In [26]:
# ones()
print(np.ones(5))
print(np.ones((2,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# full()
print(np.full(2,5))
print(np.full((2,4),10))

[5 5]
[[10 10 10 10]
 [10 10 10 10]]


In [28]:
# linspace() sirve para generar un rango de datos
print(np.linspace(2,6, num=3))
print(np.linspace(1,10,10))

[2. 4. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
# eye() crea una matriz identidad
print(np.eye(2))
print(np.eye(4))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
# random.rand() genera valores aleatorios
print(np.random.rand()) # valor aleatorio entre 0 y 1
print(np.random.rand(4))
print(np.random.rand(3,2))

0.11493577585374615
[0.87598206 0.23440841 0.58681293 0.13046963]
[[0.19340293 0.07685667]
 [0.6399773  0.04596837]
 [0.92872669 0.17426227]]


In [31]:
# random.randint() genera enteros aleatorios
print(np.random.randint(1,15)) # aleatorio entre 1 y 15
print(np.random.randint(1,10,(3,4)))

4
[[8 5 5 4]
 [1 6 1 2]
 [1 2 4 5]]


In [32]:
# random.choice() genera aleatorios de un set de datos
print(np.random.choice(['a','e','i','o','u']))
print(np.random.choice([True, False], size=(3,5)))

i
[[ True False  True False  True]
 [False  True False  True  True]
 [False False  True  True False]]


### Shape y Reshape

La función [**shape**](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) me indica la forma que tiene un arreglo.

In [33]:
# shape()
arreglo = np.random.randint(1,10,(3,2))
print(arreglo)
print(arreglo.shape)

[[3 6]
 [1 9]
 [4 4]]
(3, 2)


La función [**reshape**](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html) nos permite cambiar la forma que tenía establecida en un arreglo.

In [34]:
# reshape()
print(arreglo.reshape(1,6))

[[3 6 1 9 4 4]]


In [35]:
print(np.reshape(arreglo,(2,3)))

[[3 6 1]
 [9 4 4]]


In [36]:
print(arreglo)

[[3 6]
 [1 9]
 [4 4]]


In [37]:
# hacer un reshape como lo hace el lenguaje C
print(np.reshape(arreglo,(2,3),'C'))

[[3 6 1]
 [9 4 4]]


In [38]:
# hacer un reshape como lo hace el lenguaje FORTRAN
print(np.reshape(arreglo,(2,3),'F'))

[[3 4 9]
 [1 6 4]]


In [39]:
# hacer un reshape de acuerdo al guardado de datos en mi sistema
# decide si lo hace por medio de C o FORTRAN
print(np.reshape(arreglo,(2,3),'A'))

[[3 6 1]
 [9 4 4]]


### Funciones principales de Numpy

- [Statistics](https://numpy.org/doc/stable/reference/routines.statistics.html)
- [Matematical fuctions](https://numpy.org/doc/stable/reference/routines.math.html)

In [40]:
vector = np.random.randint(1,20,10)
print(vector)

[ 1  8 15  5  1 17  9 18  5  2]


In [41]:
# max()
print(vector.max())

18


In [42]:
matriz = vector.reshape(2,5)
print(matriz)

[[ 1  8 15  5  1]
 [17  9 18  5  2]]


In [43]:
# max()
print(matriz.max())
print(matriz.max(0)) #columna
print(matriz.max(1)) #fila

18
[17  9 18  5  2]
[15 18]


In [44]:
# argmax() nos da el indice del elemento más grande
print(vector.argmax())
print(matriz.argmax(0)) #columna
print(matriz.argmax(1)) #fila

7
[1 1 1 0 1]
[2 2]


In [45]:
# min()
print(vector.min())
print(matriz.min())
print(matriz.min(0)) #columna
print(matriz.min(1)) #fila

1
1
[ 1  8 15  5  1]
[1 2]


In [46]:
# argmin() nos da el indice del elemento más chico
print(vector.argmin())
print(matriz.argmin(0)) #columna
print(matriz.argmin(1)) #fila

0
[0 0 0 0 0]
[0 4]


In [47]:
print(vector)

[ 1  8 15  5  1 17  9 18  5  2]


In [48]:
# ptp() da la diferencia del valor más grande con el más chico
print(vector.ptp())

17


In [49]:
print(matriz)

[[ 1  8 15  5  1]
 [17  9 18  5  2]]


In [50]:
# ptp()
print(matriz.ptp(0)) #columna
print(matriz.ptp(1)) #fila

[16  1  3  0  1]
[14 16]


In [51]:
# sort() ordena de menor a mayor
vector.sort()

In [52]:
# percentile() específica el percentil a trabajar
# se necesita tener ordenados los valores del arreglo
print(vector,'\n')

print(np.percentile(vector, 0)) #percentil 0 
print(np.percentile(vector, 50)) #percentil 50 o mediana
print(np.percentile(vector, 100)) #percentil 100

[ 1  1  2  5  5  8  9 15 17 18] 

1.0
6.5
18.0


In [53]:
# median() me da la mediana de un arreglo
# la mediana es el valor que corresponde a la mitad de mi distribución
print(np.median(vector))
print(np.median(matriz, 0)) #columna
print(np.median(matriz, 1)) #fila

6.5
[ 4.5  5.   8.5 11.  11.5]
[ 2. 15.]


In [54]:
# mean() me da la media de un arreglo
print(np.mean(vector))
print(np.mean(matriz, 0)) #columna
print(np.mean(matriz, 1)) #fila

8.1
[ 4.5  5.   8.5 11.  11.5]
[ 2.8 13.4]


In [55]:
# var() me da la varianza de un arreglo
print(np.var(vector))
print(np.var(matriz, 0)) #columna
print(np.var(matriz, 1)) #fila

38.29
[12.25 16.   42.25 36.   42.25]
[ 3.36 17.04]


In [56]:
# std() me da la desviación estandar de un arreglo
print(np.std(vector))
print(np.std(matriz, 0)) #columna
print(np.std(matriz, 1)) #fila

6.187891401761993
[3.5 4.  6.5 6.  6.5]
[1.83303028 4.12795349]


In [57]:
# concatenate() nos permite unir o concatenar arreglos
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b = np.expand_dims(b, axis=0) #expandimos una dimension
np.concatenate((a,b), axis=0) # axis=0 columna

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# utilizando la transpuesta de b
np.concatenate((a,b.T), axis=1) # axis=1 fila

# si queremos concatenar algo a una columna, 
# debo ordenarlo en forma de fila y viceversa.

array([[1, 2, 5],
       [3, 4, 6]])

### Copy

Nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en el array original.

[numpy.copy](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

In [59]:
array1 = np.arange(0,11)
print(array1)
array2 = array1[0:6]
print(array2)
array2[:] = 0 #cambiamos todos los valores a 0
print(array2)
print(array1) # pero, también alteramos el array1

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [60]:
# para evitar esta clase de errores utilizamos copy()
array1 = np.arange(0,11)
print(array1)
array_copy = array1[0:6].copy() #usamos .copy()
print(array_copy)
array_copy[:] = 0 #cambiamos todos los valores a 0
print(array_copy)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[0 0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10]


### Condiciones

Cuando se quiere obtener alguna consulta específica que sea dificil de lograr por un slicing o index, usamos las condiciones.

In [61]:
arr1 = np.linspace(1,10,10, dtype='int8')
print(arr1)

#podemos obtener una lista booleana de una condicion
condicion = arr1 > 5
print(condicion)

#podemos indexar la condicion
# filtra solo los datos que estan en True
print(arr1[condicion])

print(arr1[(arr1 > 5) & (arr1 < 9)]) # se usa '&' y no 'and'

# también podemos redefinir los elementos con los filtros
arr1[arr1 < 6] = 0
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7 8]
[ 0  0  0  0  0  6  7  8  9 10]


In [62]:
# where(condicion, valor si, valor si no se cumple)
array2D = np.array([[19,  4, 43],
                    [ 8, 96, 80],
                    [ 6, 99, 35]])
print(array2D)

matriz_condicionada = np.where(array2D > 50, 0, 1)
print(matriz_condicionada)

[[19  4 43]
 [ 8 96 80]
 [ 6 99 35]]
[[1 1 1]
 [1 0 0]
 [1 0 1]]


### Operaciones

[Numpy basic operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

[Numpy broadcasting](https://www.youtube.com/watch?v=oG1t3qlzq14)

In [63]:
# operaciones en listas
lista = [1,2]
print(lista)
print(lista * 2)

[1, 2]
[1, 2, 1, 2]


In [64]:
# operaciones en arrays
arreglo1 = np.arange(0,10)
print(arr)
arreglo2 = arreglo1.copy()
print(arreglo1 * 2)
print(arreglo1 ** 3)

[1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[  0   1   8  27  64 125 216 343 512 729]


In [65]:
# tambien puedo hacer operaciones entre arrays
print(arreglo1 + arreglo2)
print(arreglo1 * arreglo2)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


In [66]:
# operaciones entre matrices
matriz1 = arreglo1.reshape(2,5)
print(matriz1)
matriz2 = matriz1.copy()

print(matriz1 + matriz2)
print(matriz1 * matriz2) #multiplicacion no matricial
print()
print(np.matmul(matriz1, matriz2.T)) #multiplicacion matricial
print(matriz1 @ matriz2.T) #producto punto
print(np.dot(matriz1, matriz2.T)) #producto punto 

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]

[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]


## Pandas

[Tutorial Pandas](https://platzi.com/blog/pandas/)

### Series y DataFrames en Pandas

Pandas maneja dos objetos principales:

- Pandas Series: Es muy parecido a un array unidimensional de Numpy, es indexado, puedo hacer slicing, se le pueden aplicar operaciones matemáticas y maneja muchos tipos de datos.


- Pandas DataFrame: Es parecido a las estructuras matriciales de Numpy o una tabla de una DB relacional. Es un objeto hecho de arrays en una estructura matricial, tenemos filas y columnas las cuales pueden ser accedidas por indices, los indices de las columnas serán los nombres de las columnas y los indices de las filas podemos asignarlo nosotros o tomar un predeterminado. También podemos hacer slicing, operaciones matemáticas, tenemos distintos tipos de datos, optimiza mucho la memoria y es de tamaño variable. 

In [67]:
# Importando la libreria pandas
import pandas as pd

In [68]:
# definiendo un panda series por medio de una lista
players1 = pd.Series(['Navas','Mbappe','Neymar','Messi'])
print(players1,'\n')

# podemos definir sus indices
players2 = pd.Series(['Navas','Mbappe','Neymar','Messi'], index=[1,7,10,30])
print(players2)

0     Navas
1    Mbappe
2    Neymar
3     Messi
dtype: object 

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object


In [69]:
# definiendo un panda series por medio de un diccionario
players3 = pd.Series({1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'})
print(players3)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object


In [70]:
# accediendo a su posición por el índice

print(players1[2], '\n')
print(players1[0:3], '\n')

print(players2[30], '\n')
print(players2[0:3], '\n')

print(players3[7], '\n')

Neymar 

0     Navas
1    Mbappe
2    Neymar
dtype: object 

Messi 

1      Navas
7     Mbappe
10    Neymar
dtype: object 

Mbappe 



In [71]:
# definiendo un dataframe por medio de un diccionario de listas
diccionario = {
    'Jugador': ['Navas','Mbappe','Neymar','Messi'],
    'Altura': [183.0,170.0,170.0,165.0],
    'Goles': [2,200,200,200]
}
 
print(pd.DataFrame(diccionario))
print()
# también podemos definir sus índices
print(pd.DataFrame(diccionario, index=[1,7,10,30]))

  Jugador  Altura  Goles
0   Navas   183.0      2
1  Mbappe   170.0    200
2  Neymar   170.0    200
3   Messi   165.0    200

   Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    200
30   Messi   165.0    200


In [72]:
# mostrando los indices del dataframe
df_Players1 = pd.DataFrame(diccionario)
print(df_Players1.columns) #indices de columnas
print(df_Players1.index) #indices de filas
print()
df_Players2 = pd.DataFrame(diccionario, index=[1,7,10,30])
print(df_Players2.columns) #indices de columnas
print(df_Players2.index) #indices de filas

Index(['Jugador', 'Altura', 'Goles'], dtype='object')
RangeIndex(start=0, stop=4, step=1)

Index(['Jugador', 'Altura', 'Goles'], dtype='object')
Int64Index([1, 7, 10, 30], dtype='int64')


In [73]:
# definiendo un dataframe por medio de una lista de diccionarios
lista = [
    {'Jugador':'Navas', 'Altura':'183.0','Goles':2},
    {'Jugador':'Mbappe', 'Altura':'170.0','Goles':200},
    {'Jugador':'Neymar', 'Altura':'170.0','Goles':200},
    {'Jugador':'Messi', 'Altura':'165.0','Goles':200}
]

print(pd.DataFrame(lista))
print()
# también podemos definir sus índices
print(pd.DataFrame(lista, index=[1,7,10,30]))

  Jugador Altura  Goles
0   Navas  183.0      2
1  Mbappe  170.0    200
2  Neymar  170.0    200
3   Messi  165.0    200

   Jugador Altura  Goles
1    Navas  183.0      2
7   Mbappe  170.0    200
10  Neymar  170.0    200
30   Messi  165.0    200


In [74]:
# mostrando los indices del dataframe
df_Players3 = pd.DataFrame(lista)
print(df_Players3.columns) #indices de columnas
print(df_Players3.index) #indices de filas
print()
df_Players4 = pd.DataFrame(lista, index=[1,7,10,30])
print(df_Players4.columns) #indices de columnas
print(df_Players4.index) #indices de filas

Index(['Jugador', 'Altura', 'Goles'], dtype='object')
RangeIndex(start=0, stop=4, step=1)

Index(['Jugador', 'Altura', 'Goles'], dtype='object')
Int64Index([1, 7, 10, 30], dtype='int64')


### Leer archivos CSV y JSON

La gran mayoría de archivos que se leen son CSV, en caso de que se leyeran de SQL, por lo general se pasan a CSV y luego traerlo a DataFrames con read_csv()

[Kaggle](https://www.kaggle.com/) es una página donde podemos encontrar una enorme cantidad de datasets con una gran diversidad de formatos. 

- [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

- [read_json](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)

In [75]:
# leyendo archivos CSV
pd.read_csv('./datos_muestra/bestsellers-with-categories.csv')
# tambien podemos utilizar el atributo sep como delimitador
pd.read_csv('./datos_muestra/bestsellers-with-categories.csv', sep=',')
# tambien podemos modificar el el encabezado o header (por default header=0)
# si el archivo no tiene ningun tipo de header, se utiliza header=None
pd.read_csv('./datos_muestra/bestsellers-with-categories.csv', sep=',', header=2) #el 2 representa la fila del archivo empezando por 0

11/22/63: A Novel  \
0              12 Rules for Life: An Antidote to Chaos   
1                               1984 (Signet Classics)   
2    5,000 Awesome Facts (About Everything!) (Natio...   
3        A Dance with Dragons (A Song of Ice and Fire)   
4    A Game of Thrones / A Clash of Kings / A Storm...   
..                                                 ...   
543       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
544  You Are a Badass: How to Stop Doubting Your Gr...   
545  You Are a Badass: How to Stop Doubting Your Gr...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   

                 Stephen King  4.6   2052  22  2011      Fiction  
0          Jordan B. Peterson  4.7  18979  15  2018  Non Fiction  
1               George Orwell  4.7  21424   6  2017      Fiction  
2    National Geographic Kids  4.8   7665  12  2019  Non Fiction  
3         George R. R. Martin  4.4  12643  11  2011      Fiction  
4         George R. R. Martin  4.7  19735  30  2014      Fiction  
..                        ...  ...    ...  ..   ...          ...  
543               Jeff Kinney  4.9   9413   8  2019      Fiction  
544               Jen Sincero  4.7  14331   8  2016  Non Fiction  
545               Jen Sincero  4.7  14331   8  2017  Non Fiction  
546               Jen Sincero  4.7  14331   8  2018  Non Fiction  
547               Jen Sincero  4.7  14331   8  2019  Non Fiction  

[548 rows x 7 columns]

In [76]:
#podemos modificar el nombre de las columnas
df_books  = pd.read_csv('./datos_muestra/bestsellers-with-categories.csv', header=0,
            names=['Nombre', 'Autor', 'Rating', 'Reseñas', 'Precio', 'Año', 'Genero'])
df_books


Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  Rating  Reseñas  Precio   Año       Genero  
0                    JJ Smith     4.7    17350       8  2016  Non Fiction  
1                Stephen King     4.6     2052      22  2011      Fiction  
2          Jordan B. Peterson     4.7    18979      15  2018  Non Fiction  
3               George Orwell     4.7    21424       6  2017      Fiction  
4    National Geographic Kids     4.8     7665      12  2019  Non Fiction  
..                        ...     ...      ...     ...   ...          ...  
545               Jeff Kinney     4.9     9413       8  2019      Fiction  
546               Jen Sincero     4.7    14331       8  2016  Non Fiction  
547               Jen Sincero     4.7    14331       8  2017  Non Fiction  
548               Jen Sincero     4.7    14331       8  2018  Non Fiction  
549               Jen Sincero     4.7    14331       8  2019  Non Fiction  

[550 rows x 7 columns]

In [77]:
# leyendo archivos JSON
pd.read_json('./datos_muestra/hpcharactersdataraw.json')
# otra forma de leerlos pero en formato raw, es con el atributo typ
pd.read_json('./datos_muestra/hpcharactersdataraw.json', typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [78]:
# También se puede llamar a el archivo directamente del servidor
url = "https://static.platzi.com/media/public/uploads/hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574.json"
pd.read_json(url)

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

### Filtrando con loc y iloc

Como Pandas esta basado en numpy podemos hacer slicing como en numpy, pero si quisieramos hacer filtros, comparaciones, modificar valores o hacer busquedas por filas y/o columnas, podemos hacer uso de los métodos iloc y loc.

In [79]:
# sclicing
df_books[0:2]

Nombre         Autor  Rating  Reseñas  Precio   Año  \
0  10-Day Green Smoothie Cleanse      JJ Smith     4.7    17350       8  2016   
1              11/22/63: A Novel  Stephen King     4.6     2052      22  2011   

        Genero  
0  Non Fiction  
1      Fiction

Si quisieramos filtrar por el eje de las columnas, podemos:

In [80]:
df_books['Autor']

df_books[['Nombre', 'Rating']]

Nombre  Rating
0                        10-Day Green Smoothie Cleanse     4.7
1                                    11/22/63: A Novel     4.6
2              12 Rules for Life: An Antidote to Chaos     4.7
3                               1984 (Signet Classics)     4.7
4    5,000 Awesome Facts (About Everything!) (Natio...     4.8
..                                                 ...     ...
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)     4.9
546  You Are a Badass: How to Stop Doubting Your Gr...     4.7
547  You Are a Badass: How to Stop Doubting Your Gr...     4.7
548  You Are a Badass: How to Stop Doubting Your Gr...     4.7
549  You Are a Badass: How to Stop Doubting Your Gr...     4.7

[550 rows x 2 columns]

#### Loc

Si quisieramos filtrar por fila y columna podemos utilizar **loc** (donde loc hace referencia a labels)

[loc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)

In [81]:
df_books.loc[:] # muestra todo el dataframe

df_books.loc[0:4] # muestras las filas del 0 al 4 con 4 inclusivo

df_books.loc[0:4, ['Nombre', 'Autor']]

Nombre                     Autor
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

Podemos realizar operaciones solo afectando los resultados filtrados por loc a nivel de labels.

In [82]:
# podemos 
df_books.loc[0:3:, ['Reseñas']] * -1

Reseñas
0   -17350
1    -2052
2   -18979
3   -21424

In [83]:
df_books.loc[1:2,['Autor']] == 'George Orwell'

Autor
1  False
2  False

#### iLoc

La diferencia con **loc** es que **iloc** trabaja por indice, es decir los números indicando las posiciones de las filas y columnas deseadas.
Los parámetros pueden ser números, rangos o listas de números.

[iloc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html)

In [84]:
df_books.iloc[:] # muestra todo el dataframe

df_books.iloc[0:4] # muestras las filas del 0 al 3 con 4 no inclusivo

df_books.iloc[0:4, 0:2] # con la columna de indice 2 no inclusivo

Nombre               Autor
0            10-Day Green Smoothie Cleanse            JJ Smith
1                        11/22/63: A Novel        Stephen King
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson
3                   1984 (Signet Classics)       George Orwell

In [85]:
df_books.iloc[:2, 2:] # primeras dos filas y quitando las primaras 2 columnas

Rating  Reseñas  Precio   Año       Genero
0     4.7    17350       8  2016  Non Fiction
1     4.6     2052      22  2011      Fiction

### Agregar o eliminar datos con Pandas

[.drop()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html)

#### Eliminando columnas

In [86]:
# eliminando columnas
df_books.drop('Reseñas', axis=1) # 0 para filas, 1 para columnas
df_books.head(2)

Nombre         Autor  Rating  Reseñas  Precio   Año  \
0  10-Day Green Smoothie Cleanse      JJ Smith     4.7    17350       8  2016   
1              11/22/63: A Novel  Stephen King     4.6     2052      22  2011   

        Genero  
0  Non Fiction  
1      Fiction

- *.drop()* retorna un dataframe con el elemento especificado eliminado, pero para borrar el elemento del dataframe original podemos utilizar el parametro *inplace=True*

In [87]:
# eliminando columnas con inplace
df_books.drop('Reseñas', axis=1, inplace=True)
df_books.head(2)

Nombre         Autor  Rating  Precio   Año  \
0  10-Day Green Smoothie Cleanse      JJ Smith     4.7       8  2016   
1              11/22/63: A Novel  Stephen King     4.6      22  2011   

        Genero  
0  Non Fiction  
1      Fiction

- Otra manera es reasignando la variable.

In [88]:
# eliminando columnas reasignando el dataframe
df_books = df_books.drop('Autor', axis=1)
df_books.head(2)

Nombre  Rating  Precio   Año       Genero
0  10-Day Green Smoothie Cleanse     4.7       8  2016  Non Fiction
1              11/22/63: A Novel     4.6      22  2011      Fiction

#### Eliminando filas

In [89]:
# eliminando filas con inplace
df_books.drop(0, axis=0, inplace=True) # 0 para filas, 1 para columnas
df_books.head(2)

Nombre  Rating  Precio   Año       Genero
1                        11/22/63: A Novel     4.6      22  2011      Fiction
2  12 Rules for Life: An Antidote to Chaos     4.7      15  2018  Non Fiction

In [90]:
# eliminando filas reasignando el dataframe
df_books = df_books.drop(1, axis=0) # 0 para filas, 1 para columnas
df_books.head(2)

Nombre  Rating  Precio   Año       Genero
2  12 Rules for Life: An Antidote to Chaos     4.7      15  2018  Non Fiction
3                   1984 (Signet Classics)     4.7       6  2017      Fiction

In [91]:
# otras formas de eliminar filas (aplica para columnas)
df_books.drop([2,3,4,5], axis=0).head(2)

df_books.drop(range(2,10), axis=0).head(2)

index_author = df_books[df_books['Año']==2010].index
df_books.drop(index_author).head(2)

Nombre  Rating  Precio   Año       Genero
2  12 Rules for Life: An Antidote to Chaos     4.7      15  2018  Non Fiction
3                   1984 (Signet Classics)     4.7       6  2017      Fiction

#### Agregando columnas

In [92]:
# creando una nueva columna
df_books['Nueva'] = np.nan 
df_books.sample(4)

Nombre  Rating  Precio   Año  \
68   Delivering Happiness: A Path to Profits, Passi...     4.6      15  2010   
52         Crazy Love: Overwhelmed by a Relentless God     4.7      14  2011   
234             Mindset: The New Psychology of Success     4.6      10  2015   
461  The Short Second Life of Bree Tanner: An Eclip...     4.6       0  2010   

          Genero  Nueva  
68   Non Fiction    NaN  
52   Non Fiction    NaN  
234  Non Fiction    NaN  
461      Fiction    NaN

Nota: Pandas implemento valores nulos dentro del mismo pandas para no tener que importar NumPy, podemos usar pd.NA y es lo mismo que np.nan

In [93]:
print(df_books.shape) # dimensiones del dataframe
print(df_books.shape[0]) # filas del dataframe
print(df_books.shape[1]) # columnas del dataframe

(548, 6)
548
6


Nota: todo rango que se asigne a una columna, debe tener la misma longitud que el resto de las columnas.

In [94]:
data = np.arange(0, df_books.shape[0])
df_books['Rango'] = data
df_books.tail(5)

Nombre  Rating  Precio   Año  \
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)     4.9       8  2019   
546  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2016   
547  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2017   
548  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2018   
549  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2019   

          Genero  Nueva  Rango  
545      Fiction    NaN    543  
546  Non Fiction    NaN    544  
547  Non Fiction    NaN    545  
548  Non Fiction    NaN    546  
549  Non Fiction    NaN    547

#### Agregando filas

[pd.concat()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html)

In [95]:
# agregando filas
df_books.append(df_books) # deprecado
#pd.concat([df_books, df_books])
#pd.concat([df_books, df_books], ignore_index=True) 
# ignore_index=True permite generar nuevos índices con el total de filas.

/tmp/ipykernel_6758/482942692.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books.append(df_books) # deprecado


Nombre  Rating  Precio   Año  \
2              12 Rules for Life: An Antidote to Chaos     4.7      15  2018   
3                               1984 (Signet Classics)     4.7       6  2017   
4    5,000 Awesome Facts (About Everything!) (Natio...     4.8      12  2019   
5        A Dance with Dragons (A Song of Ice and Fire)     4.4      11  2011   
6    A Game of Thrones / A Clash of Kings / A Storm...     4.7      30  2014   
..                                                 ...     ...     ...   ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)     4.9       8  2019   
546  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2016   
547  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2017   
548  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2018   
549  You Are a Badass: How to Stop Doubting Your Gr...     4.7       8  2019   

          Genero  Nueva  Rango  
2    Non Fiction    NaN      0  
3        Fiction    NaN      1  
4    Non Fiction    NaN      2  
5        Fiction    NaN      3  
6        Fiction    NaN      4  
..           ...    ...    ...  
545      Fiction    NaN    543  
546  Non Fiction    NaN    544  
547  Non Fiction    NaN    545  
548  Non Fiction    NaN    546  
549  Non Fiction    NaN    547  

[1096 rows x 7 columns]

Nota: Una buena practica antes del iniciar la limpieza de la data, es generar una copia profunda del DataFrame:

*df_copy = df.copy(deep=True)*, en caso de no colocar *deep=True* solo se generara una shallow copy (solo referencias de la data y el indice) y cualquier cambio del df original afectara el Shallow copy y viceversa.

### Manejo de datos nulos

Los datos nulos o datos incompletos son un dolor de cabeza en el mundo deDarta Science, sin embargo, Pandas ofrece muchas utilidades para su manejo.
- [df.isnull](https://pandas.pydata.org/docs/reference/api/pandas.isnull.html)
- [df.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html)
- [df.dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

In [96]:
import pandas as pd
import numpy as np

dicc = {
    'col1': [1,2,3,np.nan],
    'col2': [4, np.nan,6,7],
    'col3': ['a', 'b', 'c', None]
}

In [97]:
df = pd.DataFrame(dicc)
df # dataframe con valores nullos

col1  col2  col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [98]:
# muestra que valores son nulos con booleanos
df.isnull()

col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [99]:
# para llevarlo a un metodo numerico que se utilice
# en tensores y redes neuronales 
df.isnull() * 1

col1  col2  col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [100]:
# llena los valores nulos
df.fillna('Missing')

col1     col2     col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [101]:
# podemos llenar los valores nulos con cualquier funcion
df.fillna(df.mean())

/tmp/ipykernel_6758/1823426374.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


col1      col2  col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [102]:
# llena los valores nulos como si fueran elementos
# faltantes de una serie manejando valores minimos
# y maximos. Es util cuando los datos esten estructurados
# con una serie y una frecuencia exacta.
df.interpolate()

col1  col2  col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [103]:
# borra los valores nulos
df.dropna()

col1  col2 col3
0   1.0   4.0    a
2   3.0   6.0    c

### Filtrado por condiciones

In [104]:
df_books = pd.read_csv('./datos_muestra/bestsellers-with-categories.csv')
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [105]:
# generando condiciones
df_books['Year'] >= 2016

0       True
1      False
2       True
3       True
4       True
       ...  
545     True
546     True
547     True
548     True
549     True
Name: Year, Length: 550, dtype: bool

In [106]:
# filtrando condicion
df_books[df_books['Year'] >= 2016]

Name  \
0                        10-Day Green Smoothie Cleanse   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[200 rows x 7 columns]

In [107]:
# otra forma de filtrar condiciones
df_books[df_books.Year == 2016]

Name  \
0                        10-Day Green Smoothie Cleanse   
9                            A Man Called Ove: A Novel   
15   Adult Coloring Book Designs: Stress Relief Col...   
19                                  Alexander Hamilton   
36                            Between the World and Me   
37                                         Born to Run   
43   Calm the F*ck Down: An Irreverent Adult Colori...   
49   Cravings: Recipes for All the Food You Want to...   
64                      Dear Zoo: A Lift-the-Flap Book   
88              Double Down (Diary of a Wimpy Kid #11)   
100                                     Fahrenheit 451   
102  Fantastic Beasts and Where to Find Them: The O...   
112                                    First 100 Words   
124                               Giraffes Can't Dance   
151                           Hamilton: The Revolution   
153  Harry Potter and the Chamber of Secrets: The I...   
154  Harry Potter and the Cursed Child, Parts 1 & 2...   
157  Harry Potter and the Sorcerer's Stone: The Ill...   
159         Harry Potter Paperback Box Set (Books 1-7)   
163  Hillbilly Elegy: A Memoir of a Family and Cult...   
168              How to Win Friends & Influence People   
192  Jesus Calling: Enjoying Peace in His Presence ...   
202  Killing the Rising Sun: How America Vanquished...   
211                      Laugh-Out-Loud Jokes for Kids   
229                                     Milk and Honey   
235             Mindset: The New Psychology of Success   
242                                      Night (Night)   
249                          Oh, the Places You'll Go!   
268  Pokémon Deluxe Essential Handbook: The Need-to...   
278  Publication Manual of the American Psychologic...   
311                                StrengthsFinder 2.0   
326  The 5 Love Languages: The Secret to Love that ...   
336  The 7 Habits of Highly Effective People: Power...   
358              The Constitution of the United States   
377  The Four Agreements: A Practical Guide to Pers...   
383                              The Girl on the Train   
390                              The Going-To-Bed Book   
424  The Life-Changing Magic of Tidying Up: The Jap...   
431                                 The Magnolia Story   
438                           The Nightingale: A Novel   
444  The Official SAT Study Guide, 2016 Edition (Of...   
479                        The Very Hungry Caterpillar   
484  The Whole30: The 30-Day Guide to Total Health ...   
486                   The Wonderful Things You Will Be   
502  Thug Kitchen: The Official Cookbook: Eat Like ...   
508                              To Kill a Mockingbird   
523  Uninvited: Living Loved When You Feel Less Tha...   
533                            When Breath Becomes Air   
543                                             Wonder   
546  You Are a Badass: How to Stop Doubting Your Gr...   

                                 Author  User Rating  Reviews  Price  Year  \
0                              JJ Smith          4.7    17350      8  2016   
9                       Fredrik Backman          4.6    23848      8  2016   
15          Adult Coloring Book Designs          4.5     2313      4  2016   
19                          Ron Chernow          4.8     9198     13  2016   
36                     Ta-Nehisi Coates          4.7    10070     13  2016   
37                    Bruce Springsteen          4.7     3729     18  2016   
43                         Sasha O'Hara          4.6    10369      4  2016   
49                       Chrissy Teigen          4.7     4761     16  2016   
64                         Rod Campbell          4.8    10922      5  2016   
88                          Jeff Kinney          4.8     5118     20  2016   
100                        Ray Bradbury          4.6    10721      8  2016   
102                        J.K. Rowling          4.7     4370     15  2016   
112                        Roger Priddy          4.7    17323      4  2016   

In [108]:
# multiples condiciones con &
df_books[(df_books['Genre'] == 'Fiction') & (df_books['Year'] > 2016)]

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [109]:
# filtrando con negacion con ~
df_books[~(df_books['Year'] < 2018)] # mayor o igual a 2018

Name  \
2              12 Rules for Life: An Antidote to Chaos   
4    5,000 Awesome Facts (About Everything!) (Natio...   
8        A Higher Loyalty: Truth, Lies, and Leadership   
13                    A Wrinkle in Time (Time Quintet)   
32                                            Becoming   
..                                                 ...   
534                            Where the Crawdads Sing   
536  Whose Boat Is This Boat?: Comments That Don't ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                               Author  User Rating  Reviews  Price  Year  \
2                  Jordan B. Peterson          4.7    18979     15  2018   
4            National Geographic Kids          4.8     7665     12  2019   
8                         James Comey          4.7     5983      3  2018   
13                  Madeleine L'Engle          4.5     5153      5  2018   
32                     Michelle Obama          4.8    61133     11  2018   
..                                ...          ...      ...    ...   ...   
534                       Delia Owens          4.8    87841     15  2019   
536  The Staff of The Late Show with
          4.6     6669     12  2018   
545                       Jeff Kinney          4.9     9413      8  2019   
548                       Jen Sincero          4.7    14331      8  2018   
549                       Jen Sincero          4.7    14331      8  2019   

           Genre  
2    Non Fiction  
4    Non Fiction  
8    Non Fiction  
13       Fiction  
32   Non Fiction  
..           ...  
534      Fiction  
536  Non Fiction  
545      Fiction  
548  Non Fiction  
549  Non Fiction  

[100 rows x 7 columns]

### Funciones principales de Pandas

[10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html)

In [110]:
# obtener informacion de las columnas
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [111]:
# resumen estadistico del dataframe
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [112]:
# ultimas filas del dataframe
df_books.tail(3)

Name       Author  \
547  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
547          4.7    14331      8  2017  Non Fiction  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

In [113]:
# filas aleatorias
df_books.sample(3)

Name          Author  User Rating  \
114                         First 100 Words    Roger Priddy          4.7   
79                    Doctor Sleep: A Novel    Stephen King          4.7   
303  Strange Planet (Strange Planet Series)  Nathan W. Pyle          4.9   

     Reviews  Price  Year        Genre  
114    17323      4  2018  Non Fiction  
79     15845     13  2013      Fiction  
303     9382      6  2019      Fiction

In [114]:
# cuanta memoria utilizamos en el dataframe
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [115]:
# contar las coincidencias por columna
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [116]:
# eliminar registros duplicados
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [117]:
# eliminar duplicados, pero borra todos menos el ultimo 
df_books.drop_duplicates(keep='last')

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [118]:
# ordenar los registros según la columna especificada
df_books.sort_values('Year')

Name            Author  \
177                                      I, Alex Cross   James Patterson   
131  Glenn Beck's Common Sense: The Case Against an...        Glenn Beck   
417                                   The Last Lecture      Randy Pausch   
241                       New Moon (The Twilight Saga)   Stephenie Meyer   
72       Diary of a Wimpy Kid: The Last Straw (Book 3)       Jeff Kinney   
..                                                 ...               ...   
150                                               Guts  Raina Telgemeier   
466  The Subtle Art of Not Giving a F*ck: A Counter...       Mark Manson   
462                                 The Silent Patient  Alex Michaelides   
130  Girl, Wash Your Face: Stop Believing the Lies ...     Rachel Hollis   
549  You Are a Badass: How to Stop Doubting Your Gr...       Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
177          4.6     1320      7  2009      Fiction  
131          4.6     1365     11  2009  Non Fiction  
417          4.7     4028      9  2009  Non Fiction  
241          4.6     5680     10  2009      Fiction  
72           4.8     3837     15  2009      Fiction  
..           ...      ...    ...   ...          ...  
150          4.8     5476      7  2019  Non Fiction  
466          4.6    26490     15  2019  Non Fiction  
462          4.5    27536     14  2019      Fiction  
130          4.6    22288     12  2019  Non Fiction  
549          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [119]:
# ordenar los registros de manera descenciente
df_books.sort_values('Year', ascending=False)

Name                 Author  \
549  You Are a Badass: How to Stop Doubting Your Gr...            Jen Sincero   
294  School Zone - Big Preschool Workbook - Ages 4 ...            School Zone   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)        Naomi Kleinberg   
130  Girl, Wash Your Face: Stop Believing the Lies ...          Rachel Hollis   
..                                                 ...                    ...   
418  The Last Olympian (Percy Jackson and the Olymp...           Rick Riordan   
38           Breaking Dawn (The Twilight Saga, Book 4)        Stephenie Meyer   
92   Eat This, Not That! Thousands of Simple Food S...        David Zinczenko   
139  Good to Great: Why Some Companies Make the Lea...            Jim Collins   
299                                  Sookie Stackhouse       Charlaine Harris   

     User Rating  Reviews  Price  Year        Genre  
549          4.7    14331      8  2019  Non Fiction  
294          4.8    23047      6  2019  Non Fiction  
489          4.9     8842     10  2019      Fiction  
263          4.7    10820      5  2019  Non Fiction  
130          4.6    22288     12  2019  Non Fiction  
..           ...      ...    ...   ...          ...  
418          4.8     4628      7  2009      Fiction  
38           4.6     9769     13  2009      Fiction  
92           4.3      956     14  2009  Non Fiction  
139          4.5     3457     14  2009  Non Fiction  
299          4.7      973     25  2009      Fiction  

[550 rows x 7 columns]

### groupby

Agrupamientos o funciones de agregacion (separar categorias pertenecientes a una sola columna)


[df.groupby()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)

Vamos a agrupar por ciertas características o columnas y aparte nos llevamos una función de agregación total o a ciertas columnas en específico.

In [120]:
# saber cuantos registro hay por author
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [121]:
# la categoría a agrupar pasa a ser el indice del df
df_books.groupby('Author').sum().loc['William Davis']

User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [122]:
# Obteniendo los valores planos
df_books.groupby('Author').sum().reset_index()

Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [123]:
# podemos aplicar varias funciones de agregación
df_books.groupby('Author').agg(['min', 'max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [124]:
# podemos especificar las columnas y funciones de agregacion a aplicar.
df_books.groupby('Author').agg({
    'Reviews': ['min', 'max'],
    'User Rating': 'sum'
})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [125]:
# podemos hacer más de una agrupacion tomando en cuenta su posicion
df_books.groupby(['Author', 'Year']).count() 

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

### Combinando DataFrames

[Comparación con SQL](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html)

Así como en la teoria de conjuntos y SQL, tenemos distintas formas de combinar nuestros dataframes.

- *Left join*: Da prioridad al dataframe de la izquierda. Trae siempre los datos de la izquierda y las filas en común con el dataframe de la derecha.
- *Right join*: Da prioridad al dataframe de la derecha. Trae siempre los datos de la derecha y las filas en común con el dataframe de la izquierda.
- *Inner join*: Trae solamente aquellos datos que son común en ambos dataframe.
- *Outer join*: Trae los datos del dataframe de la izquierda como el de la derecha, incluyendo los datos que ambos comparten.

Otra manera para combinar dataframes es el método *concat()* ya sea a nivel de filas (*axis=0*) o de columnas (*axis=1*).

Pueden haber valores NaN debido a que la organización por columnas no respeta la estructura que puedan tener ambos dataframes.

### Merge y Concat

[**Concat**](https://pandas.pydata.org/docs/reference/api/pandas.concat.html)

In [126]:
df1 = pd.DataFrame({
    'A': ['a0', 'a1', 'a2', 'a3'],
    'B': ['b1', 'b1', 'b2', 'b3'],
    'C': ['c0', 'c1', 'c2', 'c3'],
    'D': ['d0', 'd1', 'd2', 'd3'],
})

df2 = pd.DataFrame({
    'A': ['a4', 'a5', 'a6', 'a7'],
    'B': ['b4', 'b5', 'b6', 'b7'],
    'C': ['c4', 'c5', 'c6', 'c7'],
    'D': ['d4', 'd5', 'd6', 'd7'],
})

In [127]:
# Concat a nivel de filas
pd.concat([df1, df2]) # default axis=0

A   B   C   D
0  a0  b1  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [128]:
# Corrigiendo los indices de la concatenación
pd.concat([df1, df2], ignore_index=True)

A   B   C   D
0  a0  b1  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5
6  a6  b6  c6  d6
7  a7  b7  c7  d7

In [129]:
# Concat a nivel de columnas
pd.concat([df1, df2], axis=1) # axis=1

A   B   C   D   A   B   C   D
0  a0  b1  c0  d0  a4  b4  c4  d4
1  a1  b1  c1  d1  a5  b5  c5  d5
2  a2  b2  c2  d2  a6  b6  c6  d6
3  a3  b3  c3  d3  a7  b7  c7  d7

[**Merge**](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

In [130]:
df_izquierda =  pd.DataFrame({
    'I': ['i0', 'i1', 'i2', 'i3'],
    'J': ['j0', 'j1', 'j2', 'j3'],
    'K': ['k0', 'k1', 'k2', 'k3']
})

df_derecha =  pd.DataFrame({
    'I': ['i0', 'i1', 'i2', 'i3'],
    'L': ['l0', 'l1', 'l2', 'l3'],
    'M': ['m0', 'm1', 'm2', 'm3'],
})

In [131]:
# Combinar de izquierda a derecha
df_izquierda.merge(df_derecha)

I   J   K   L   M
0  i0  j0  k0  l0  m0
1  i1  j1  k1  l1  m1
2  i2  j2  k2  l2  m2
3  i3  j3  k3  l3  m3

In [132]:
# es conveniente especificar la columna sobre la que se hara el merge
df_izquierda.merge(df_derecha, on='I')

I   J   K   L   M
0  i0  j0  k0  l0  m0
1  i1  j1  k1  l1  m1
2  i2  j2  k2  l2  m2
3  i3  j3  k3  l3  m3

In [133]:
df_derecha =  pd.DataFrame({
    'II': ['i0', 'i1', 'i2', 'i3'],
    'L': ['l0', 'l1', 'l2', 'l3'],
    'M': ['m0', 'm1', 'm2', 'm3'],
})

In [134]:
# Si no hay columnas en común
df_izquierda.merge(df_derecha, left_on='I', right_on='II')

I   J   K  II   L   M
0  i0  j0  k0  i0  l0  m0
1  i1  j1  k1  i1  l1  m1
2  i2  j2  k2  i2  l2  m2
3  i3  j3  k3  i3  l3  m3

In [135]:
df_derecha =  pd.DataFrame({
    'II': ['i0', 'i1', 'i2', np.nan],
    'L': ['l0', 'l1', 'l2', 'l3'],
    'M': ['m0', 'm1', 'm2', 'm3'],
})

In [136]:
# si hay elementos NaN dentro de las columnas para hacer
# match, por lo que solo trae las coincidencias (inner join)
# omitiendo la fila de indice 3.
df_izquierda.merge(df_derecha, left_on='I', right_on='II')

I   J   K  II   L   M
0  i0  j0  k0  i0  l0  m0
1  i1  j1  k1  i1  l1  m1
2  i2  j2  k2  i2  l2  m2

In [137]:
print(df_izquierda, '\n')
print(df_derecha)

    I   J   K
0  i0  j0  k0
1  i1  j1  k1
2  i2  j2  k2
3  i3  j3  k3 

    II   L   M
0   i0  l0  m0
1   i1  l1  m1
2   i2  l2  m2
3  NaN  l3  m3


In [138]:
# Para traernos el resto de valores usamos how
# que nos permite decir el tipo de merge a aplicar
df_izquierda.merge(df_derecha, left_on='I', right_on='II',
                   how='left') # left join

I   J   K   II    L    M
0  i0  j0  k0   i0   l0   m0
1  i1  j1  k1   i1   l1   m1
2  i2  j2  k2   i2   l2   m2
3  i3  j3  k3  NaN  NaN  NaN

In [139]:
df_izquierda.merge(df_derecha, left_on='I', right_on='II',
                   how='right') # right join

I    J    K   II   L   M
0   i0   j0   k0   i0  l0  m0
1   i1   j1   k1   i1  l1  m1
2   i2   j2   k2   i2  l2  m2
3  NaN  NaN  NaN  NaN  l3  m3

### Join

Es otra herramienta que nos ofrece pandas para hacer una cobinación.

La diferencia con *merge* es que *join* va ir directamente a los **indices** con los que trabajamos los dataframes y no a columnas específicas.

En temas de performance y velocidad cuando se trata de miles de registros [*join*](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html) suele ser mejor.

In [140]:
izq = pd.DataFrame({
    'A': ['a0', 'a1', 'a2'],
    'B': ['b0', 'b1', 'b2']
}, index=['k0', 'k1', 'k2'])

der = pd.DataFrame({
    'C': ['c0', 'c1', 'c2'],
    'D': ['d0', 'd1', 'd2']
}, index=['k0', 'k2', 'k3'])

In [141]:
# Left join (default)
izq.join(der)

A   B    C    D
k0  a0  b0   c0   d0
k1  a1  b1  NaN  NaN
k2  a2  b2   c1   d1

In [142]:
# Inner join
izq.join(der, how='inner')

A   B   C   D
k0  a0  b0  c0  d0
k2  a2  b2  c1  d1

In [143]:
# Right join
izq.join(der, how='right')

A    B   C   D
k0   a0   b0  c0  d0
k2   a2   b2  c1  d1
k3  NaN  NaN  c2  d2

In [144]:
# Outer join
izq.join(der, how='outer')

A    B    C    D
k0   a0   b0   c0   d0
k1   a1   b1  NaN  NaN
k2   a2   b2   c1   d1
k3  NaN  NaN   c2   d2

### Pivot y Melt

*pivot* y *melt* son dos funciones que sirven para cambiar la estructura de nuestro DataFrame a nuestras necesidades.

**pivot_table**

Esta función puede traer recuerdos a las personas interesadas en SQL, ya que diversos motores de Bases de Datos la tienen implementada. Pivot, básicamente, transforma los valores de determinadas columnas o filas en los índices de un nuevo DataFrame, y la intersección de estos es el valor resultante.

In [145]:
df_books = pd.read_csv('./datos_muestra/bestsellers-with-categories.csv', sep=',', header=0)

In [146]:
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [147]:
# Aplicando pivot_table
df_books.pivot_table(index='Author', columns='Genre', values='User Rating')
# los valores de Author pasan a formar el índice por fila
# y los valores de Genre forman parte de los índices por 
# columna, y User Rating se mantiene como valor.

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [148]:
df_books.pivot_table(index='Genre', columns='Year', values='User Rating', aggfunc='median')
# Podemos cambiar el parámetro aggfunc que traduce función de agrupamiento.

Year         2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  2019
Genre                                                                        
Fiction       4.7  4.70   4.7   4.6  4.65   4.7   4.8   4.8   4.8   4.8  4.85
Non Fiction   4.6  4.55   4.6   4.6  4.60   4.6   4.7   4.7   4.6   4.7  4.70

**melt**

El método *melt* toma las columnas del DataFrame y las pasa a filas, con dos nuevas columnas para especificar la antigua columna y el valor que traía.

In [149]:
df_books[['Name', 'Genre']].head()

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [150]:
# Aplicando melt
df_books[['Name', 'Genre']].head().melt()
# Ahora cada resultado de las dos columnas pasa
# a una fila de este modo a tipo llave:valor.

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [151]:
df_books.melt(id_vars='Year', value_vars='Genre')
# Con id_vars seleccionamos las columnas que no queremos hacer melt.
# Con value_vars selecciona la única columna que le aplica melt.

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

### Apply

[Apply](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) es un método que nos ayuda a aplicar funciones a nuestro DataFrame, con funciones nos referimos a funciones previamente definidas en Python.

Así podemos aplicar distintas funciones matemáticas, de consulta, modificación de datos, etc. 

In [155]:
# definimos una funcion
def two_times(value):
    return value * 2

In [156]:
# le pasamos como argumento la definicion de la funcion
df_books['User Rating'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ... 
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [157]:
# tambien podemos aplicarle funciones lambda
df_books['User Rating'].apply(lambda x: x * 2)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ... 
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [161]:
# Apply en varias columnas con condiciones
df_books.apply(lambda x: x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis=1)
# es más rapido que un for

0      4.7
1      9.2
2      4.7
3      9.4
4      4.8
      ... 
545    9.8
546    4.7
547    4.7
548    4.7
549    4.7
Length: 550, dtype: float64